### ISSUE TITLE
Getting FileNotFoundError

### ISSUE THREAD

**Issue by HeshamHBK** [Th0h0/autossrf#2]
Hi guys, 

I did all the steps for installation but I still get the following error: 

 Traceback (most recent call last):
  File "autossrf.py", line 11, in <module>
    os.chdir(currentPath)
FileNotFoundError: [Errno 2] No such file or directory: ''

Please help!

**Comment by Th0h0** [comment]
`currentPath` consists of autossrf.py's path. It's quite weird that it's not recognized.
Could you paste the full error? No such file or directory: "...."?

**Comment by HeshamHBK** [comment]
what a wrote above is the full error.

I Typed: python3 autossrf.py -h
OUTPUT: 

Traceback (most recent call last):
  File "autossrf.py", line 11, in <module>
    os.chdir(currentPath)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by fernstedt** [comment]
Its been 6 months,

still the same error

**Comment by rbcrack** [comment]
If you still have problem, do this

`#execPath = os.getcwd()
#currentPath = os.path.dirname(__file__)
#os.chdir(currentPath)`

rpelace it with this

`execPath = os.getcwd()
currentPath = os.path.dirname(__file__) if __file__ else None

if currentPath:
    os.chdir(currentPath)`
